### ISSUE TITLE
Local setup on Debian 12 with jar file not working

### ISSUE THREAD

**Issue by vdbhb59** [LinkoraApp/sync-server#1]
I followed the steps, and since Stirling-PDF also works the same way, I guessed it will too.
However, I found a few issues:
* Every time I run the java file `java -jar linkoraSyncServer-0.0.1.jar`, it asks to setup the config file over and over again. The config file even if either created manually, or created on first launch. It just keeps on asking to config.
* This is what it shows: [Paste](https://pb.flossboxin.org.in/?af618f52c28466fb#7kiexaJtwvo7Nj8oFVJewADJDoshGdz6JX956VVHmjfp)
* Even if I have given password during setup, or if I have configured the file manually, it does not work.
* I am not using any database, so I am sure default is PGSQL, which should be auto setup by the server file.

Is there some permission that is needed, or a specific user? Do I need to chmod +x, or change the owner & group?
My owner & groups are either root:root or user:www-data.

Probably show your setup permissions and user+group?
FYI: Java 21 is installed, and Stirling-PDF works without any issue.
I do not use docker, so using java file.

**Comment by sakethpathike** [comment]
from the log:
```
...
Database driver not found for jdbc:/linkora

Configure the `linkoraConfig.json` file to properly set up the server and database connection.
...
```
What is the URL you've provided for `databaseUrl`? It should be something like `mysql:path-to-db`, `sqlite:path-to-db`, or a similar format, depending on the database you're using. It shouldn't be just `/linkora`. Also, you don't need to prepend `jdbc:`, the server will add it automatically.

The `databaseUrl` of my config file looks like `postgresql://someAddress:port/linkora`.

> It just keeps on asking to config.

It'll throw it if it cannot connect to the provided database. There might be an issue with `databaseUrl`. Make sure it's not just `/linkora` but a complete and valid path.


> Is there some permission that is needed, or a specific user?

Nah, it doesn't need any permission, and it doesn't need to be executable. It works just by running the `jar` command, and the jar is fine since it starts the Ktor application (as per the logs).

**Comment by vdbhb59** [comment]
Thanks. I tried, but now I am getting this. FYI, I am not a developer, so I maybe doing some mistake for sure.
[Paste](https://pb.flossboxin.org.in/?69095bcd984cab32#ptPJ8t2gb6ihtYmAq4YiSTApSL9yfZnsytaNVLKbcL5)

This is my config file:
`{
    "databaseUrl": "pgsql:localhost:5432/linkora",
    "databaseUser": "linkora",
    "databasePassword": "pwdhere",
    "hostAddress": "0.0.0.0",
    "serverPort": 45454,
    "serverAuthToken": ""
}`

**Comment by sakethpathike** [comment]
ah, no problem.  

The `databaseUser` should be the username of the database you're using, not `linkora`. This isn't specific to the server but to the database itself. Usually, it's `root`.  

`databasePassword` is the password for the actual database you're connecting to.  

Also, I remember you mentioned you're on SQLite. It doesn't need username and password. Are you still using it? If so, your `databaseUrl` should be something like:

```
sqlite:/home/saketh/Documents/sqlite/databaseFileName
```
Now, just as an example, I've created this in `Documents`. You can have the database file anywhere, just pass it as `databaseUrl`. The setup will create a DB file specific to Linkora in the same folder where the jar is located.  

Now, remove the values for both user and password in the config file, which should then look like this:  
```
"databaseUser": "", 
"databasePassword": ""
```

Also, if you're unable to locate the existing database file, open SQLite via the terminal. It should then say something like:  
`Connected to a transient in-memory database.`  

Next, run:  
```
.open SOME_FILE_NAME
```
Close the terminal.  

Now, `databaseUrl` should be similar to:  
```
sqlite:/home/saketh/Documents/sqlite/SOME_FILE_NAME
```


and run the server once again 🙌🏻.

**Comment by sakethpathike** [comment]
@vdbhb59 what database you're using? I forgot to ask this before 😅

**Comment by sakethpathike** [comment]
Ah, alright, I overlooked the info that you gave (or probably forgot 😅) that you're on PGSQL (AFAIK, that's PostgreSQL).

Now, `databaseUrl` should be:
```
postgresql://localhost:5432/linkora
```
The `databaseUser` should be the username of the PostgreSQL (PGSQL) instance running on your machine.

`databasePassword` should be the password for this PostgreSQL instance.

If there's no password for the user, remove the `databasePassword` value:
```
"databasePassword": "",
```

re-run the jar file now.

**Comment by sakethpathike** [comment]
@vdbhb59 any update?

**Comment by vdbhb59** [comment]
Sorry, office and other house chores..

I retried both as postgres system user and the separate database I created. For both, it does start, however the web page is blank, and I get a bunch of new errors. See this [paste](https://pb.flossboxin.org.in/?d36156c424f491f4#4aTwMx815MWeen624LZF51juNKR7FZVAtRpHkBPR8dUy)

The webpage is also "blank/white" and nothing loads, not even the favicon. I am sure there is some permission, or some setting that is missing. 😢

See the page..

![Image](https://github.com/user-attachments/assets/e0d52367-418f-466d-8517-8de0308b404b)

**Comment by sakethpathike** [comment]
actually it's working 😅😹, it's just that I didn’t add any favicons or frontend to this (this is only meant for exchanging data between the database on your system and the Linkora app), so it won't show anything. but seeing the logs, it's clear that the server is up and running as expected.


the reason webpages are blank is that i've only thought to use them for communication between the Linkora app and server, so it only shares information related to that.

Now, if you're on desktop, then in Linkora app, go to Settings -> Data -> Connect to Server, and pass the server URL (change the server host in the config to the local ipv4 of your machine and pass it as the server URL instead of http://0.0.0.0:45454, or just delete the config file and rerun the server, this address will be set up automatically) and also pass the auth token that you set for this server and connect to it. Linkora app will handle everything else.

if you're on mobile, then connect to the same Wi-Fi the system is on and do the same process as above for connecting to the server. This way, the Android app can communicate with it.

i think I should change that to something instead of a blank page 😅. also, is there anything else that you think should have been added that would have made this thing easier?

**Comment by vdbhb59** [comment]
It does connect via the client. So great 😄.. I will add the `systemd` setup and maybe couple of more things, once I get it completely up and running over on self-host.
Okay, few or maybe several things here.
* Only IP address for host works. Else it gives unexpected address error.
* Only http works, and that is insecure tbvh, and should have rather a URL against it in https mode. TLS error comes if `https://ip` is given.
* Where are the files & folders located on the server and also locally? What path should I look at? I have it hosted on a root server over at my hosting provider.
* When I create a folder or even a link on the desktop app, it does create one, but it also throws some error over. Remote execution failed, 404 not found (see image below).

Something else as well I believe, but while writing, I forgot. lols

![Image](https://github.com/user-attachments/assets/90b79a1d-8357-44ea-ba6e-03b6a110075b)

**Comment by sakethpathike** [comment]
> Only IP address for host works. Else it gives unexpected address error.

yeah, I think localhost doesn’t work, so only the IP should be used. I should update this in the README too 😅.

> Only http works

yeah, if using locally, it needs a verified certificate from CA to connect via HTTPS. The other way is to manually generate one and add it to trusted certificates. I’ll see what I can do about this soon.

if on remote the cloud provider will take care of this, so it should work as expected.

> Where are the files & folders located on the server and also locally?

preferences and database files are stored in your home directory, in a folder named `.linkora`. It’s usually hidden by the system but can be seen if you enable "Show Hidden Files" or something like that.

> When I create a folder or even a link on the desktop app, it does create one, but it also throws some error over. Remote execution failed, 404 not found (see first image below).

i think I’ve included a wrong route for testing the connection on the app that doesn’t exist on the server. I remember removing a route but probably didn’t delete it on the client. I’ll fix this in the next release.

> When I click on sync manually (since I am not sure it is syncing automatically or not), the second image error comes up.

that particular route is handled by the app for updates, so if the server has no updates, it returns an empty list, which is probably why this pops up. I’ll remove that pop-up once I get some time.

> When I try to (after a relaunch of the desktop app) create a folder and save it, it keeps on buffering. 

this is probably an issue with the Room database. is it happening even after relaunching the app after this behavior 🤔

**Comment by vdbhb59** [comment]
> > Only IP address for host works. Else it gives unexpected address error.
> 
> yeah, I think localhost doesn’t work, so only the IP should be used. I should update this in the README too 😅.

But if we have https (I do have a url, and the web page as you can see), I would like to use the secured connection, right?

> 
> > Only http works
> 
> yeah, if using locally, it needs a verified certificate from CA to connect via HTTPS. The other way is to manually generate one and add it to trusted certificates. I’ll see what I can do about this soon.

Exactly, as this will surely help a lot. I do have the certs, and my apache2 & nginx are already forwarded to https, just need a way to get it to work on the jar file env configs as well. Probably Stirling-PDF settings can be looked upon to see how he has done the code for it?

> 
> if on remote the cloud provider will take care of this, so it should work as expected.

Once I get a env variable to use it, should be fine, I guess.

> 
> > Where are the files & folders located on the server and also locally?
> 
> preferences and database files are stored in your home directory, in a folder named `.linkora`. It’s usually hidden by the system but can be seen if you enable "Show Hidden Files" or something like that.

Cool. Will check out my server end too tomorrow.

> > When I try to (after a relaunch of the desktop app) create a folder and save it, it keeps on buffering.
> 
> this is probably an issue with the Room database. is it happening even after relaunching the app after this behavior 🤔

Yes, thrice I tried, and it keeps trying to create. I will recheck tomorrow and let you know once more.

**Comment by sakethpathike** [comment]
> But if we have https

it should work, I'm currently using render instead of local hosting and i do connect to it via https 🤔

**Comment by vdbhb59** [comment]
> > But if we have https
> 
> it should work, I'm currently using render instead of local hosting and i do connect to it via https 🤔

So, how do I connect via https? I use apache2 & nginx.

> 
> > Will check out my server end too tomorrow.
> 
> the server only needs its config file, which it saves in the directory where the jar exists, but now that you've mentioned it, i think I should have placed all of these in one folder 😅. i'll implement this in upcoming versions.
> 
> at this point, that `.linkora` folder in the home directory is only meant for the app

So, at server level, where do I store my folders and links? What is the path mate? Debian 12.

**Comment by sakethpathike** [comment]
> So, how do I connect via https?

i passed it as `https://url` for the render. i think you can do the same, but since you mentioned it wasn't successful, i should check what i'm supposed to do.

> So, at server level, where do I store my folders and links?

the server will handle it in the database you're currently connected to. you don't need to do anything manually, just make sure both the server and database are up and properly connected.

> then where is it stored when an android phone connects to the server?

it is stored in the external database, which in your case is PGSQL

> so I am presuming that database file is on server

the database will be created within the database service you connect to, which in your case is the PGSQL

> Apologies for asking so many questions

actually, i should've made things clearer in the readme 😅😅. i'll do it soon.

i've created this workflow of these connected things, which should make it easier to understand how everything works:

![Image](https://github.com/user-attachments/assets/bb2d9b7e-92c4-41ed-82d3-ad821cc65638)

https://excalidraw.com/#json=kxSytW-fK7jHVPfCQiYtE,pn7RTDHIus5UXUb72X_b9g

**Comment by vdbhb59** [comment]
I would like to add the systemd portion as well. It works for me, and will work for anyone else as well. Let me know. Meanwhile, I will report few more bugs I guess. Desktop app on relaunch says 404 not found (for server), and have to be retried / rechecked from the data settings to be connected.
Folder creation is still the same as above, so still stuck.

**Comment by sakethpathike** [comment]
> I would like to add the systemd portion as well. It works for me, and will work for anyone else as well. 

oh, in that case, can you please fork this repo, add the required stuff in the readme, and make a PR when you have some time? i'll merge it once i'm back online.

> Desktop app on relaunch says 404 not found (for server)

yeahhh, this is definitely because the client checks for a route (TEST_BEARER) that doesn't exist on the server in this version.
 
![Image](https://github.com/user-attachments/assets/93c55518-ff38-4697-bc64-396529cfd743)

i've re-added this route, so the next version of the server should fix this.

>  Folder creation is still the same as above, so still stuck.

can't really do anything about this :( as this is handled by room database, i should probably switch from room to manual handling or something else

**Comment by vdbhb59** [comment]
FYI, giving an update:
So, I upgraded the server-sync to the latest. After that I opened the desktop app, and it gives 404 not found. I even ran the server setup once more on the desktop app and relaunched, but the same.

Also, these 3 errors still happen (https://github.com/LinkoraApp/sync-server/issues/1#issuecomment-2653735265)

![Image](https://github.com/user-attachments/assets/1a3f2f6a-bd1c-4783-812e-84cea571ed9f)

**Comment by sakethpathike** [comment]
this is  weird  🤔, this also means it didn't connect to the server (considering the server is up and running)

i'm also on 0.0.2, but I didn't face this issue

![Image](https://github.com/user-attachments/assets/3a5ca35e-d24b-4c89-a094-05bf5d37a64a)

---

there's probably something wrong on the client side, i'll check it soon

**Comment by vdbhb59** [comment]
We can close this out, and raise if the issues continue in the next versions.
